using UnityEngine;

public class LigneArrivee : MonoBehaviour
{
    [Header("R√©f√©rence du chronom√®tre")]
    public Chronometre chrono;

    private bool chronoEnCours = false;
    private bool cooldown = false;

    private void OnCollisionEnter(Collision collision)
    {
        if (!cooldown && collision.gameObject.CompareTag("Car"))
        {
            cooldown = true;
            Invoke(nameof(ReinitialiserCooldown), 1f);

            if (!chronoEnCours)
            {
                chrono.DemarrerChrono();
                chronoEnCours = true;
                Debug.Log("üö¶ D√©but du chrono !");
            }
            else
            {
                chrono.ArreterChrono();
                Debug.Log("üèÅ Tour termin√© !");
            }
        }
    }

    private void ReinitialiserCooldown()
    {
        cooldown = false;
    }
}
